export const centres = [
  {
    options: [
      { value: 'Internal Quality Assurance Cell (IQAC)', label: 'Internal Quality Assurance Cell (IQAC)' },
      { value: "Office of the Deans of Student Affairs / Students' Union", label: "Office of the Deans of Student Affairs / Students' Union" },
      { value: 'Office of the Deans of Academic Affairs', label: 'Office of the Deans of Academic Affairs' },
      { value: 'Stella Maris Research and International Partnerships Centre (SMRIPC)', label: 'Stella Maris Research and International Partnerships Centre (SMRIPC)' },
      { value: 'Stella Maris Centre for Development of Resources for Inclusion and Vocational Enrichment (SMCDRIVE)', label: 'Stella Maris Centre for Development of Resources for Inclusion and Vocational Enrichment (SMCDRIVE)' },
      { value: 'Stella Maris Centre for Human Resource Development (SMCHRD)', label: 'Stella Maris Centre for Human Resource Development (SMCHRD)' },
      { value: 'Industry Connect (ICON)', label: 'Industry Connect (ICON)' },
      { value: 'Consortium of Higher Education Institutions for Research and Development (CHIRD)', label: 'Consortium of Higher Education Institutions for Research and Development (CHIRD)' },
      { value: 'DST-FIST', label: 'DST-FIST' },
      { value: 'The Centre for Research in Science and Technology (CRIST)', label: 'The Centre for Research in Science and Technology (CRIST)' },
      { value: 'Centre for Women’s Studies (CWS)', label: 'Centre for Women’s Studies (CWS)' },
      { value: 'Incubation Centre', label: 'Incubation Centre' },
      { value: 'Stella Maris College Gender Centre (SMC-GC)', label: 'Stella Maris College Gender Centre (SMC-GC)' },
      { value: 'Stella Maris College Extension Project Centre (SMCEPC)', label: 'Stella Maris College Extension Project Centre (SMCEPC)' },
      { value: 'Alumnae Association of Stella Maris College (AASMC)', label: 'Alumnae Association of Stella Maris College (AASMC)' },
      { value: 'Career Guidance Cell (CGC)', label: 'Career Guidance Cell (CGC)' },
      { value: 'Library', label: 'Library' },
      { value: 'Administrative Office', label: 'Administrative Office' },
      { value: 'Stella Maris Sustainable Development Students Hub (SMSD)', label: 'Stella Maris Sustainable Development Students Hub (SMSD)' },
      { value: 'SMC Think Tank', label: 'SMC Think Tank' },
      { value: 'Stella Maris Association of Retired Teachers (SMART)', label: 'Stella Maris Association of Retired Teachers (SMART)' },
      { value: 'St. Francis of Assisi Centre for Peace Studies', label: 'St. Francis of Assisi Centre for Peace Studies' },
      { value: 'Shanthi Bhavan Stella Maris Social Welfare Centre', label: 'Shanthi Bhavan Stella Maris Social Welfare Centre' },
      { value: 'SMC Pathway', label: 'SMC Pathway' },
      { value: 'Mentoring', label: 'Mentoring' },
    ],
  },
];

export const clubs = [
  {
    options: [
      { value: 'French Club – Cercle de Francophiles', label: 'French Club – Cercle de Francophiles' },
      { value: 'Mime & Street Theatre', label: 'Mime & Street Theatre' },
      { value: 'Classical Dance', label: 'Classical Dance' },
      { value: 'Photography and Film-making', label: 'Photography and Film-making' },
      { value: 'Dramatics', label: 'Dramatics' },
      { value: 'Quiz, Debate & Current Affairs', label: 'Quiz, Debate & Current Affairs' },
      { value: 'Enviro Club', label: 'Enviro Club' },
      { value: 'Rotaract Club', label: 'Rotaract Club' },
      { value: 'Event Management', label: 'Event Management' },
      { value: 'Sanskrit Club – Kala Kriti', label: 'Sanskrit Club – Kala Kriti' },
      { value: 'Folk Dance', label: 'Folk Dance' },
      { value: 'Stellaeidoscope', label: 'Stellaeidoscope' },
      { value: 'Hindi Club – Anubuthi', label: 'Hindi Club – Anubuthi' },
      { value: 'Tamil Club – Bharathi Mandram', label: 'Tamil Club – Bharathi Mandram' },
      { value: 'Light Music', label: 'Light Music' },
      { value: 'Western Music', label: 'Western Music' },
      { value: 'Damini', label: 'Damini' },
      { value: 'Western Dance', label: 'Western Dance' },
      { value: 'BIS Standards', label: 'BIS Standards' },
      { value: 'Silambam', label: 'Silambam' },
      { value: 'Girl Up', label: 'Girl Up' },
      { value: 'Anti Drug Abuse Club', label: 'Anti Drug Abuse Club' },
      { value: 'Unicef on Campus', label: 'Unicef on Campus' },
    ],
  }
];

export const units = [
  {
    options: [
      { value: 'Physical Education', label: 'Physical Education' },
      { value: 'National Cadet Corps (NCC)', label: 'National Cadet Corps (NCC)' },
      { value: 'National Service Scheme (NSS)', label: 'National Service Scheme (NSS)' },
      { value: 'Youth Red Cross (YRC)', label: 'Youth Red Cross (YRC)' },
      { value: 'Red Ribbon Club (RRC)', label: 'Red Ribbon Club (RRC)' },
    ],
  }
];


export const departments = [
  {
    options: [
      { value: 'BioInformatics', label: 'BioInformatics' },
      { value: 'Biotechnology', label: 'Biotechnology' },
      { value: 'Botany', label: 'Botany' },
      { value: 'Chemistry', label: 'Chemistry' },
      { value: 'Computer Science', label: 'Computer Science' },
      { value: 'Economics', label: 'Economics' },
      { value: 'Mathematics', label: 'Mathematics' },
      { value: 'Physics', label: 'Physics' },
      { value: 'Psychology', label: 'Psychology' },
      { value: 'Zoology', label: 'Zoology' },
      { value: 'Commerce - General - Shift I', label: 'Commerce - General - Shift I' },
      { value: 'Commerce - General - Shift II', label: 'Commerce - General - Shift II' },
      { value: 'Commerce - Corporate Secretaryship', label: 'Commerce - Corporate Secretaryship' },
      { value: 'Commerce - Accounting & Finance', label: 'Commerce - Accounting & Finance' },
      { value: 'Commerce - Honours', label: 'Commerce - Honours' },
      { value: 'Commerce - Business Administration', label: 'Commerce - Business Administration' },
      { value: 'Commerce - Banking, Finance and Entrepreneurship', label: 'Commerce - Banking, Finance and Entrepreneurship' },
      { value: 'Fine Arts', label: 'Fine Arts' },
      { value: 'History', label: 'History' },
      { value: 'Human Resource Management', label: 'Human Resource Management' },
      { value: 'International Studies', label: 'International Studies' },
      { value: 'Languages - Tamil', label: 'Languages - Tamil' },
      { value: 'Languages - Hindi', label: 'Languages - Hindi' },
      { value: 'Languages - French', label: 'Languages - French' },
      { value: 'Languages - Sanskrit', label: 'Languages - Sanskrit' },
      { value: 'Public Relations', label: 'Public Relations' },
      { value: 'Social Work - UG', label: 'Social Work - UG' },
      { value: 'Social Work - PG', label: 'Social Work - PG' },
      { value: 'Sociology', label: 'Sociology' },
      { value: 'Value Education', label: 'Value Education' },
      { value: 'Vocational - Banking, Financial Services and Insurance', label: 'Vocational - Banking, Financial Services and Insurance' },
      { value: 'Vocational - Food Processing and Quality Control', label: 'Vocational - Food Processing and Quality Control' },
      { value: 'Vocational - Sustainable Energy Management', label: 'Vocational - Sustainable Energy Management' },
    ],
  },
];

export const categories = [
  { value: "Conference", label: "Conference" },
  { value: "Workshop", label: "Workshop" },
  { value: "Seminar", label: "Seminar" },
  { value: "Guest Lecture", label: "Guest Lecture" },
  { value: "Certificate Course", label: "Certificate Course" },
  { value: "Scholar-in-Residence", label: "Scholar-in-Residence" },
  { value: "Book Release", label: "Book Release" },
  { value: "Exhibition", label: "Exhibition" },
  { value: "Faculty Development Programme (FDP)", label: "Faculty Development Programme (FDP)" },
  { value: "Department Fest", label: "Department Fest" },
  { value: "Sport Activity", label: "Sport Activity" },
  { value: "Cultural Activity", label: "Cultural Activity" },
  { value: "Competition", label: "Competition" },
  { value: "OAT Event", label: "OAT Event" },
  { value: "Collaborative Activity", label: "Collaborative Activity" },
  { value: "Signing of Memorandum of Understanding", label: "Signing of Memorandum of Understanding" },
  { value: "Field Trip / Excursion", label: "Field Trip / Excursion" },
  { value: "Book Discussion", label: "Book Discussion" },
  { value: "Religious / Value Education Related Event", label: "Religious / Value Education Related Event" },
  { value: "Orientation / Induction Programme", label: "Orientation / Induction Programme" },
  { value: "Conclave", label: "Conclave" },
  { value: "Alumnae Meet", label: "Alumnae Meet" }
];

export const themes = [
  { value: "slow-learners", label: "Programme for Slow Learners (2.2.1)" },
  { value: "advanced-learners", label: "Programme for Advanced Learners (2.2.1)" },
  { value: "innovation", label: "Innovation (3.3.1)" },
  { value: "research-methodology", label: "Research Methodology (3.3.2)" },
  { value: "ipr", label: "Intellectual Property Rights (IPR) (3.3.2)" },
  { value: "skill-development", label: "Skill Development (3.3.2)" },
  { value: "entrepreneurship", label: "Entrepreneurship (3.3.2)" },
  { value: "consultancy", label: "Consultancy (3.5.2)" },
  { value: "outreach", label: "Extension / Outreach Programme (3.6.3)" },
  { value: "research-collaboration", label: "Research Collaboration (3.7.1)" },
  { value: "faculty-exchange", label: "Faculty Exchange Programme (3.7.1)" },
  { value: "student-exchange", label: "Student Exchange Programme (3.7.1)" },
  { value: "mou-activity", label: "Activity under MoU (3.7.2)" },
  { value: "soft-skills", label: "Soft Skills (5.1.3)" },
  { value: "language-communication", label: "Language and Communication Skills (5.1.3)" },
  { value: "life-skills", label: "Life Skills (Yoga, Physical Fitness, Health and Hygiene etc.) (5.1.3)" },
  { value: "tech-awareness", label: "Awareness of Trends in Technology (5.1.3)" },
  { value: "competitive-exam", label: "Coaching / Guidance for Competitive Exam (5.1.4)" },
  { value: "career-guidance", label: "Career Guidance / Counselling (5.1.4)" },
  { value: "sports-event", label: "Sports Event / Competition (5.3.3)" },
  { value: "cultural-event", label: "Cultural Event / Competition (5.3.3)" },
  { value: "alumnae-engagement", label: "Alumnae Engagement Programme (5.4.1)" },
  { value: "professional-development", label: "Professional Development for Teaching & Non-Teaching Staff (6.3.3)" },
  { value: "women-empowerment", label: "Women Empowerment / Gender Equity (7.1.1)" },
  { value: "environmental-activity", label: "Beyond the Campus Environmental Promotional Activity (7.1.6)" },
  { value: "cultural-diversity", label: "Inclusion of Cultural / Regional / Linguistic / Communal / Other Diversity (7.1.8)" },
  { value: "responsible-citizenship", label: "Transformation of Students to Responsible Citizenship (7.1.9)" },
  { value: "ethics-programme", label: "Programme on Professional Ethics (7.1.10)" },
  { value: "commemorative-days", label: "National / International Commemorative Days & Festivals (7.1.11)" },
  { value: "sustainability", label: "Sustainability (7.2.1)" }
];